# Generated by Django 3.1.2 on 2022-04-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0003_auto_20220407_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_manages_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='parsingbpmn.asset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='parsingbpmn.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Actor_manage_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.actor')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process')),
            ],
        ),
    ]
