# Generated by Django 3.1.2 on 2022-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0011_asset_process_bpmn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='process_bpmn_id',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
