# Generated by Django 3.1.2 on 2022-03-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0012_auto_20220318_1843'),
    ]

    operations = [



    ]
